GR04 Фомирование коммитов рефакторинга
clearcode-tech/code-guides pull request #14
Opened 2021-07-20 09:26 UTC by yunikita

2021-07-20 12:42 UTC, bovin-a requested changes

2021-07-20 12:42 UTC, bovin-a commented on git/gr04_refactoring-commits.md
> +## Git Rule: Формирование коммитов рефакторинга
Указываем номер правила
```
Git Rule 4: ...
```

2021-07-20 12:42 UTC, bovin-a commented on git/gr04_refactoring-commits.md
> +К рефакторингу относятся изменения, которые не влияют на работу кода, только на его качество.
Не очень звучит "не влияют на работу кода". Изменение кода влияет на его работу. Ты имеешь ввиду, что логический результат выполнения кода не меняется. И в третей части предложения стоит явно повторить слово ", а влияют".
```
К рефакторингу относятся изменения, которые не влияют на логический результат работы кода,
а влияют только на его качество.
```

2021-07-20 12:42 UTC, bovin-a commented on git/gr04_refactoring-commits.md
> +  - "Правки после ревью" и "Доработка оформления" - это примеры плохих сообщений коммитов. Они не отражают суть изменений и позволяют смешивать в одном коммите слишком много разнообразных изменений.
"Правки после ревью" - полностью согласен, что это плохое сообщение.
"Доработка оформления кода" - тут чуть менее согласен, т.к. в этом случае сильно зависит уже от того, что вошло в коммит. Возможно, что не было намешано много в коммит, а действительно простые изменения оформления, типа пустых строк и переносов.

2021-07-20 12:42 UTC, bovin-a commented on git/gr04_refactoring-commits.md
> +- Не смешивать в коммитах изменения кода, которые влияют на его работу, и рефакторинг.
Тут опять же нужно чуть по другому, чтобы семантика была не влияние на работу, а влияние на логический результат работы кода. Сам рефакторинг может быть таким, что например использовался deprecated метод по UUID, а изменился на метод по типизированному ID. С точки зрения кода это прямо совсем другой метод теперь вызывается, но результат остаётся тот же самый. При этом то, что результат осатётся тот же самый - может быть на разных уровнях - в одном случае остался тот же самый результат в рамках одного метода, а в другом случае остался тот же самый результат в каком-то более крупном блоке.
```
Не смешивать в коммитах изменения кода, которые влияют на логический результат работы кода,
и рефакторинг.
```

2021-07-20 12:42 UTC, bovin-a commented on git/gr04_refactoring-commits.md
> +- Не смешивать в коммитах изменения кода, которые влияют на его работу, и рефакторинг.
Глобальный вопрос. Мы хотим рефакторинг вынести как отдельную активность, которая выполнятся в отдельных задачах. По идее смешивания просто не может быть.

2021-07-20 12:42 UTC, bovin-a commented on git/gr04_refactoring-commits.md
> +- Любой рефакторинг, подразумевающий изменения сразу в нескольких участках/файлах кода должен быть в отдельном коммите. Примеры изменений, которые точно должны быть в отдельных коммитах:
Запятая
```
кода, должен
```

2021-07-20 12:42 UTC, bovin-a commented on git/gr04_refactoring-commits.md
> +- Во время разбиения на коммиты заботиться о человеке, который будет ревьюить эти изменения. То есть каждый рефакторинг должно быть так же легко читать и ревьюить, как и выполнять.
Слово `ревьювить` так себе звучит и читается. Предложение заменить его другими формулировками:
```
... заботиться о человеке, который будет выполнять ревью этих изменений.
То есть проводить ревью изменений по каждому рефакторингу должно быть так же легко, как и
выполнять их.
```

2021-11-11 16:03 UTC, ivan-anderson commented on git/gr04_refactoring-commits.md
> +- Во время разбиения на коммиты заботиться о человеке, который будет ревьюить эти изменения. То есть каждый рефакторинг должно быть так же легко читать и ревьюить, как и выполнять.
`как и выполнять`

2021-11-11 16:35 UTC, ivan-anderson commented on git/gr04_refactoring-commits.md
> +Проблему, которую решает данная статья - сложность чтения и ревью коммитов, которые связаны с рефакторингом. Простота, которую предоставляет IDE для рефакторинга, меняет восприятие разработчика на сл
Тут всё же дело не в простоте рефакторинга с помощью IDEA, потому что массовая замена текста и тп фичи при ревью не мешают, если они отдельно зафиксированны. Проблема это в том, что в ходе разработки ты держишь все изменения в голове и если их не документируешь отдельными коммитами, то отследить последовательность изменений через CVS уже будет крайне сложно.

2021-11-11 16:35 UTC, ivan-anderson commented on git/gr04_refactoring-commits.md
> +      Переименование метода SomeService#someMethod1() в SomeService#anotherMethod1().
Не перебор ли с оформлением?

2022-02-10 04:52 UTC, WhiteBearSpirit commented
ПР переехал [сюда](https://github.com/clearcode-tech/code-guides/pull/35), этот ПР будет удалён после слития нового.

2022-03-30 08:00 UTC, merged