HRL-703 (Code style) Формализовать правила порядка, именования и комментариев полей классов
clearcode-tech/code-guides pull request #15
Opened 2021-08-13 13:55 UTC by WhiteBearSpirit

2021-08-22 17:28 UTC, bovin-a requested changes

2021-08-22 17:28 UTC, bovin-a commented on commons/cr02_class-fields-order.md
> +## Common Rule: Порядок полей класса
Common Rule 4:

2021-08-22 17:28 UTC, bovin-a commented on commons/cr02_class-fields-order.md
> +### Поля в классе располагать в алфавитном порядке.
@yunikita Это же касается только сервисов? Для классов моделей и DTO это не касается же?

2021-08-22 17:28 UTC, bovin-a commented on commons/cr04_commenting.md
> +- `@Override` методов, т.к. комментарий должен быть в базовом классе.
Добавить, что комментарий над переопределённым методом можно и нужно писать, если нужно указать специфику реализации метода.

2021-08-22 17:28 UTC, bovin-a commented on commons/cr04_commenting.md
> +- Можно не комментировать поля, если это сложные классы (репозитории, сервисы, клиенты и т.д.). Более специфичные поля всё равно обязательно комментировать (в моделях, DTO и т.д.)
Нудно убрать посыл "можно не комментировать".
```
- Поля классов, если это сложные классы, такие как репозитории, сервисы, клиенты и т.д. Хорошим
признаком того, что поле не нуждается в комментарии, является то, что значения для поля заполняется
средствами DI-контейнера автоматически (т.е. используется аннотация `@Inject`). Более специфичные
поля в классах нуждаются в комментировании, например, поля в классах моделей, DTO и т.д.
```
Список где не нужно комментить и список где нужно комментить по ходу будем расширять, когда будем видеть, что что-то забыли.

2021-08-22 17:28 UTC, bovin-a commented on commons/cr04_commenting.md
> -- Стоит переиспользовать одни и те же фразы, чтобы описать одну и ту же сущность. Например, комментарии конструкторов - это комментарий класса, к которому добавлено слово "Конструктор". Это позволяет
Не будем удалять это целиком. Нужно немного фокус поменять.

Стоит переиспользовать один и те же фразы или слова, когда описание касается чего-то, что уже было где-то упомянуто. Это позволяет:
 ... то что было до этого ...

2021-08-23 09:39 UTC, yunikita commented on commons/cr02_class-fields-order.md
> +### Поля в классе располагать в алфавитном порядке.
Да, тоже считаю только для сервисов. В моделях и DTO важно группировать по смыслу.

2021-09-07 15:09 UTC, bovin-a requested changes

2021-09-08 06:57 UTC, merged