JR 05 Именования для обработки событий
clearcode-tech/code-guides pull request #19
Opened 2021-09-16 14:30 UTC by lera12518

2021-11-11 16:51 UTC, ivan-anderson requested changes

2021-11-11 16:51 UTC, ivan-anderson commented on backend/java/jr05_event-naming.md
> +## Java Rule 5: Именования для обработки событий
Забыла добавить в README

2021-11-11 16:51 UTC, ivan-anderson commented on backend/java/jr05_event-naming.md
> +* Kafka **{Какое событие}** On **{Какое событие}** Handler -> `KafkaDocumentSigningOnFileSigningSucceededEventHandler`
Если тупо идти по тексту, то у меня бы получилось имя KafkaMyEventOnMyEventHandler

Я случайно сделал такое же правило, которое позже удалю из пул реквеста. Там я написал так:
```
- event: предназначения события + Event. Например, **DocumentPrintFormCreated**Event.
- topic: предназначения события + Event. Например, **DocumentPrintFormCreated**Topic.
- publisher: Kafka + полное название события + Publisher. Например, Kafka**DocumentPrintFormCreated**EventPublisher.
- handler: логика обработчика + On + полное название события + Handler. Например, SendNotificationOn**DocumentPrintFormCreated**EventHandler.
- subscriber: Kafka + полное название обработчика c заменой Handler на Subscriber. Например, KafkaSendNotificationOn**DocumentPrintFormCreated**EventSubscriber.
- provider: полное название подписчика + Provider.  Например, KafkaSendNotificationOn**DocumentPrintFormCreated**EventSubscriberProvider.
```

2021-11-11 16:51 UTC, ivan-anderson commented on backend/java/jr05_event-naming.md
> +2. При формировании имени группы по правилу eventHandlerClassName.replace(“Handler”, ““) + “Group“ возникает проблема неуникальности в рамках всей системы, поэтому для веб-сокетов правило чуть дораба
Не френдли описание `eventHandlerClassName.replace(“Handler”, ““) + “Group“` , особенно сбивает с толку то, что отличается от стилистики формирований выше.

2021-11-26 08:53 UTC, ivan-anderson approved these changes

2021-11-26 12:00 UTC, lera12518 commented on README.md
> +- [JR06: Именования для обработки событий](backend/java/jr06_event-naming.md)
Ветка JR05, а PR в итоге с заголовком JR06 из-за конфликта с другой задачей, в которой уже было правило JR05

2021-11-26 15:28 UTC, WhiteBearSpirit requested changes

2021-11-26 15:28 UTC, WhiteBearSpirit commented on backend/java/jr06_event-naming.md
> +## Java Rule 6: Именования для обработки событий
Как-то не гладко звучит. Может,
`Именование обработчиков событий`
или
`Именование сущностей, связанных с событиями`?

2021-11-26 15:28 UTC, WhiteBearSpirit commented on backend/java/jr06_event-naming.md
> +* **{Какое событие}** Handler -> `DocumentSigningRedirectEventHandler`
Добавить строку с описанием Publisher?

2021-11-26 15:28 UTC, WhiteBearSpirit commented on backend/java/jr06_event-naming.md
> +## Java Rule 6: Именования для обработки событий
Или просто `События`

2021-11-30 07:24 UTC, lera12518 commented on backend/java/jr06_event-naming.md
> +* **{Какое событие}** WebSocketEventSubscriberGroup -> `documentSigningRedirectEventWebSocketEventSubscriberGroup`
нет, правильно documentSigningRedirectEventWebSocketEventSubscriberGroup

2021-11-30 07:26 UTC, lera12518 commented on backend/java/jr06_event-naming.md
> +## Java Rule 6: Именования для обработки событий
мне нравится Именования для обработки событий(
Именование обработчиков событий - мы же добавили именование паблишеров, так что не обработчиков
События - мало инфы
Именование сущностей, связанных с событиями - более подходящий, но текущий такой же по сути

2021-11-30 07:29 UTC, lera12518 commented on backend/java/jr06_event-naming.md
> +* **{Какое событие}** Handler -> `DocumentSigningRedirectEventHandler`
у вебсокетов нет паблишеров у нас в проекте, сложно пока что представить, по какой причине они появятся
не хватало payload, добавила

2021-11-30 10:35 UTC, WhiteBearSpirit commented on backend/java/jr06_event-naming.md
> +## Java Rule 6: Именования для обработки событий
У меня глаз зацепился за то, что "Именование" неожиданно во множественном числе, а также я ожидал что будет сказано, именование **чего**?
Возможно, будет третье мнение)

2021-11-30 10:39 UTC, WhiteBearSpirit commented on backend/java/jr06_event-naming.md
> +* **{Какое событие}** Handler -> `DocumentSigningRedirectEventHandler`
хм, для меня это было неожиданно.

2021-11-30 10:50 UTC, WhiteBearSpirit commented on backend/java/jr06_event-naming.md
> +* **{Какое событие}** WebSocketEventSubscriberGroup -> `documentSigningRedirectEventWebSocketEventSubscriberGroup`
Хм, у нас в коде есть:
- 4 примера `WebSocketEventSubscriberGroup` без `Event` перед ним.
- 1 пример `EventWebSocketSubscriberGroup`.
- 0 примеров `EventWebSocketEventSubscriberGroup`.

Мне последний вариант кажется наиболее странным, первые два норм. Наверное, лучше всего второй.

2021-12-02 23:25 UTC, ivan-anderson commented on backend/java/jr06_event-naming.md
> +* Kafka **{Какое событие}** Publisher -> `KafkaDocumentSigningOnFileSigningSucceededEventHandler`
изменить окончание в примере на Publisher

2021-12-09 06:24 UTC, KateTarasowa approved these changes

2021-12-09 06:24 UTC, KateTarasowa commented on backend/java/jr06_event-naming.md
> +Пример подключения издателя: `publishers.addBinding().to(KafkaSendNotificationOnDocumentPrintFormCreatedEventSubscriberProvider.class);`.
там же еще вторая часть есть
`        this.bind(new TypeLiteral<Publisher<DocumentPrintFormCreatedEvent>>() { })
            .to(KafkaSendNotificationOnDocumentPrintFormCreatedEventSubscriberProvider.class);`

2021-12-09 06:28 UTC, KateTarasowa approved these changes

2021-12-09 06:28 UTC, KateTarasowa commented on backend/java/jr06_event-naming.md
> +KafkaPubSubModule размещается в _.../pubsub_kafka_.
Может стоит указать, что В начале может быть имя сервера, например, EkdKafkaPubSubModule

2021-12-09 06:28 UTC, KateTarasowa commented on backend/java/jr06_event-naming.md
> +- subscriber: Создаётся в том же модуле, где и обработчик. Место размещения _ru/ekd/server_ekd/pubsub_kafka/subscribers_
стоит убрать _ru/ekd/server_ekd /и заменить на .../

2021-12-09 07:51 UTC, KateTarasowa requested changes

2021-12-09 07:51 UTC, KateTarasowa commented on backend/java/jr06_event-naming.md
> +## Java Rule 6: Именования для обработки событий
События и места их обитания

2021-12-09 08:14 UTC, lera12518 commented on backend/java/jr06_event-naming.md
> +## Java Rule 6: Именования для обработки событий
Создание и расположение сущностей, связанных с обработкой событий

2021-12-09 13:04 UTC, WhiteBearSpirit requested changes

2021-12-09 13:04 UTC, WhiteBearSpirit commented on backend/java/jr06_event_naming_and_location.md
> +* **{Какое событие}** WebSocketEventSubscriberGroup -> `documentSigningRedirectWebSocketEventSubscriberGroup`
Я понял, что этот вариант всё-таки плох тем, что у всех сущностей имя состоит из `KafkaDocumentSigningRedirectEvent`, а для SubscriberGroup этот стиль ломается.
К тому же **{Какое событие}** уже имеет в себе суффикс Event.

То есть я считаю правильным:
> **{Какое событие}** WebSocketSubscriberGroup -> `documentSigningRedirectEventWebSocketSubscriberGroup`

2021-12-09 13:04 UTC, WhiteBearSpirit commented on backend/java/jr06_event_naming_and_location.md
> +- handler: Создаётся в том модуле, где происходит приём события. Место размещения .../business_logic/pubsub.
тоже курсивом

2021-12-09 15:06 UTC, lera12518 commented on backend/java/jr06_event_naming_and_location.md
> +* **{Какое событие}** WebSocketEventSubscriberGroup -> `documentSigningRedirectWebSocketEventSubscriberGroup`
суть в том, что это событие вебсокета, то есть WebSocketEvent

2021-12-09 15:35 UTC, WhiteBearSpirit commented on backend/java/jr06_event_naming_and_location.md
> +* **{Какое событие}** WebSocketEventSubscriberGroup -> `documentSigningRedirectWebSocketEventSubscriberGroup`
Да понимаю... беда.
Ну тогда **{Какое событие без суффикса Event}** WebSocketEventSubscriberGroup

2021-12-13 12:35 UTC, WhiteBearSpirit approved these changes

2021-12-19 11:30 UTC, mpashinsky approved these changes

2021-12-22 07:21 UTC, KateTarasowa approved these changes

2021-12-22 07:22 UTC, merged