Hrl 1066
clearcode-tech/code-guides pull request #21
Opened 2021-10-17 11:11 UTC by ivan-anderson

2021-10-20 12:21 UTC, WhiteBearSpirit commented on backend/java/jr06_transfer_object_type.md
> +- DTO - для перемещения данных между сервисами, а так же между backend-UI.
Я б сказал "для передачи данных между серверами". Потому что когда я вижу "сервис" в контексте нашего бека - то думаю в первую очередь о модельных сервисах, где данные передаются обычными классами.

2021-10-20 12:26 UTC, WhiteBearSpirit commented on backend/java/jr06_transfer_object_type.md
> +Используется на всех уровнях. Размещается в _.../controllers_dto_ если объект не уходит глубже ControllerService, иначе в _.../business_logic/dto_.
Вопрос: у меня было впечатление, что на уровне "глубже ControllerService" мы стараемся не использовать DTO. И если используем - то в качестве исключения, как legacy или чтобы не писать одинаковые классы. Это так?

2021-10-20 12:39 UTC, WhiteBearSpirit commented on backend/java/jr06_transfer_object_type.md
> +- Data - может быть частью Cache. Может использоваться в бизнес-логике. Отличается от DTO тем, что в качестве полей может иметь @Entity.
Не нашёл у нас ни одного класса *Data с аннтацией @Entity. Я бы не стал считать это ключевым отличием.
И внутри Cache использование тоже не очевидно, можно пример?
По-моему, основное применение классов *Data - для передачи внутри бизнес-логики, когда нужно подчеркнуть, что это данные для какой-то цели. Например, WebSocketData.
А ещё есть некоторые классы *Data, которые по сути DTO, но случайно были названы Data.

2021-10-20 12:41 UTC, WhiteBearSpirit commented on backend/java/jr06_transfer_object_type.md
> +- Raw - для извлечения данных из БД. Используется в репозитории. Аннотируется @Entity и @Sql. Размещается в _.../business_logic/models_.
Raw - непонятно, что имеется в виду.
Классы *RawSqlRow и *RawSqlCount ?

2021-10-20 14:06 UTC, yunikita commented on backend/java/jr06_transfer_object_type.md
> +- Data - может быть частью Cache. Может использоваться в бизнес-логике. Отличается от DTO тем, что в качестве полей может иметь @Entity.
Отвечу только по одному вопросу - "Не нашёл у нас ни одного класса *Data с аннтацией @entity." - потому что их нет. Изначальная суть этой фразы  была в том, что внутри DTO не может быть полей, которые являются объектами, полученными из БД, а в *Data как раз могут быть в полях объекты, которые были получены из БД.

2021-11-10 18:18 UTC, ivan-anderson commented on backend/java/jr07_kafka_objects.md
> +## Java Rule 7: Объекты Kafka
Такое правило уже написано и ожидает ревью в JR05 Именования для обработки событий #19. Просто дополнить его при слитии

2021-11-25 22:27 UTC, ivan-anderson commented on backend/java/jr06_transfer_object_type.md
> +Используется на всех уровнях. Размещается в _.../controllers_dto_ если объект не уходит глубже ControllerService, иначе в _.../business_logic/dto_.
Я себе представляю, что может быть контроллер принимающий ДТО, данные которого не нужно валидировать и они попадаю в ControllerService и там извлекаются и идут в какой-нибудь менеджер.

2021-11-25 22:35 UTC, ivan-anderson commented on backend/java/jr06_transfer_object_type.md
> +- Data - может быть частью Cache. Может использоваться в бизнес-логике. Отличается от DTO тем, что в качестве полей может иметь @Entity.
> 

И внутри Cache использование тоже не очевидно, можно пример?

2021-11-25 22:36 UTC, ivan-anderson commented on backend/java/jr06_transfer_object_type.md
> +- Data - может быть частью Cache. Может использоваться в бизнес-логике. Отличается от DTO тем, что в качестве полей может иметь @Entity.
`И внутри Cache использование тоже не очевидно, можно пример?`

2021-11-25 22:38 UTC, ivan-anderson commented on backend/java/jr06_transfer_object_type.md
> +- Raw - для извлечения данных из БД. Используется в репозитории. Аннотируется @Entity и @Sql. Размещается в _.../business_logic/models_.
Да

2021-11-29 05:34 UTC, WhiteBearSpirit requested changes

2021-11-29 05:34 UTC, WhiteBearSpirit commented on README.md
> +- [JR05: Создание валидаторов и обработчиков запроса](backend/java/jr05_action_and_validator.md)
JR05 и JR06 уже появились в предыдущих ПР. А 6,7,8 - в следующих. Думаю, лучше здесь сразу использовать 9, 10.

2021-11-29 05:34 UTC, WhiteBearSpirit commented on backend/java/jr05_action_and_validator.md
> +## Java Rule 5: Создание интерфейсов валидаторов и обработки запросов
JR05 и JR06 уже появились в предыдущих ПР. А 6,7,8 - в следующих.  Думаю, лучше здесь сразу использовать 9.
(и имя файла не забыть)

2021-11-29 05:34 UTC, WhiteBearSpirit commented on backend/java/jr06_transfer_object_type.md
> +## Java Rule 6: Виды объектов для передачи данных между слоями
JR05 и JR06 уже появились в предыдущих ПР. А 6,7,8 - в следующих. Думаю, лучше здесь сразу использовать 10.
(и имя файла не забыть)

2021-11-29 05:34 UTC, WhiteBearSpirit commented on backend/java/jr05_action_and_validator.md
> +   * @param <S> Тип данных, являющийся контекстом запроса.
являющи**х**ся
(или в пред. строчке исправить наоборот)

2021-11-29 05:34 UTC, WhiteBearSpirit commented on backend/java/jr05_action_and_validator.md
> +   * @param <S> Тип данных, являющийся контекстом запроса.
являющи**х**ся
(если выбираем такой вариант)

2021-11-29 05:34 UTC, WhiteBearSpirit commented on backend/java/jr06_transfer_object_type.md
> +- Raw - для извлечения данных из БД. Используется в репозитории. Аннотируется @Entity и @Sql. Размещается в _.../business_logic/models_.
Запиши сюда эти примеры

2021-11-29 05:34 UTC, WhiteBearSpirit commented on backend/java/jr06_transfer_object_type.md
> +- DTO - для перемещения данных между серверами, а так же между backend и UI.
также
(слитно)

2021-11-29 05:41 UTC, WhiteBearSpirit commented on backend/java/jr06_transfer_object_type.md
> +Используется на всех уровнях. Размещается в _.../controllers_dto_ если объект не уходит глубже ControllerService, иначе в _.../business_logic/dto_.
Просто по факту сейчас DTO у нас ходят аж до репозитория (например, `DocumentRegistryFilterDTO` в `DocumentRepository`).
Вот хочу понять, это нормально и тогда это надо тут отобразить, или это ненормально, и тогда надо придумать - как было бы правильно?

2021-11-29 06:55 UTC, mpashinsky approved these changes

2021-11-30 07:49 UTC, lera12518 approved these changes

2021-11-30 07:49 UTC, lera12518 commented on backend/java/jr05_action_and_validator.md
> +Используемые методы в функциональном интерфейсах `T apply(...)` или `void accept(...)`
функциональных

2021-11-30 07:49 UTC, lera12518 commented on commons/cr04_commenting.md
> +- Конструкторов классов. Если в конструкторе используется неочевидный параметр, который бы хотелось пояснить,
который хотелось бы пояснить

2021-11-30 10:24 UTC, WhiteBearSpirit commented on commons/cr04_commenting.md
> +- Поля стандартных интерфейсов параметризованных нашими объектами. Например, `Provider<KafkaApplicationGroupFilesSigningFailedSubscriber> subscriber`.
Над MatDialogRef коммент нужен. Пруф:
https://bitbucket.org/ekd-dev/ekd-ui/pull-requests/273/hrl-1123#comment-257738451

2021-11-30 10:26 UTC, WhiteBearSpirit commented on commons/cr04_commenting.md
> +- Поля стандартных интерфейсов параметризованных нашими объектами. Например, `Provider<KafkaApplicationGroupFilesSigningFailedSubscriber> subscriber`.
А над `_store: Store<AppState>` не нужен.

2021-12-07 16:37 UTC, ivan-anderson commented on README.md
> +- [JR05: Создание валидаторов и обработчиков запроса](backend/java/jr05_action_and_validator.md)
я их подгоню под свобондые номера на момент выхода, чтобы не оставлять пустых слотов.

2021-12-07 16:37 UTC, ivan-anderson commented on backend/java/jr05_action_and_validator.md
> +## Java Rule 5: Создание интерфейсов валидаторов и обработки запросов
решу конфликт в момент слития

2021-12-09 06:34 UTC, KateTarasowa approved these changes

2021-12-09 06:34 UTC, KateTarasowa commented on commons/cr04_commenting.md
> +- Полей **стандартных** интерфейсов параметризованных нашими объектами. Например, `Provider<KafkaApplicationGroupFilesSigningFailedSubscriber> subscriber` и `Store<AppState>`.
Стоит добавить как пример-исключение: MatDialogRef<NotificationSettingDlgComponent>

2021-12-09 09:41 UTC, WhiteBearSpirit approved these changes

2021-12-09 20:47 UTC, ivan-anderson commented on commons/cr04_commenting.md
> +- Полей **стандартных** интерфейсов параметризованных нашими объектами. Например, `Provider<KafkaApplicationGroupFilesSigningFailedSubscriber> subscriber` и `Store<AppState>`.
это и так список исключений, описывать исключения для исключений не перебор?

2021-12-19 11:26 UTC, mpashinsky approved these changes

2021-12-24 13:00 UTC, KateTarasowa approved these changes

2021-12-24 22:16 UTC, ivan-anderson commented on backend/java/jr06_transfer_object_type.md
> +Используется на всех уровнях. Размещается в _.../controllers_dto_ если объект не уходит глубже ControllerService, иначе в _.../business_logic/dto_.
это необходимость из-за того, что мы не можем в методе делать более 5 параметров

2021-12-27 08:32 UTC, merged