HRL-1146 Добавить правило про сортировку методов
clearcode-tech/code-guides pull request #26
Opened 2021-10-28 23:24 UTC by ivan-anderson

2021-11-26 08:50 UTC, lera12518 approved these changes

2021-11-29 06:00 UTC, WhiteBearSpirit requested changes

2021-11-29 06:00 UTC, WhiteBearSpirit commented on backend/java/jr08_sorting_methods.md
> +Это значит, что нужно придерживаться размещения публичных методов по принципу: первые идут методы создания, после них методы чтения, потом методы обновления и нижние методы удаления.
нижние методы удаления - странновато, предлагаю
"в конце - методы удаления".

2021-11-29 06:00 UTC, WhiteBearSpirit commented on backend/java/jr08_sorting_methods.md
> +public void updateClientUser(...) {...}
`public ClientUser updateClientUser`
(возращаем модель после обновления)

2021-11-29 06:00 UTC, WhiteBearSpirit commented on backend/java/jr08_sorting_methods.md
> +- Модельный сервис
.
.
.
(ставим точки в конце пунктов списка)

2021-11-29 06:50 UTC, mpashinsky approved these changes

2021-12-09 06:35 UTC, KateTarasowa approved these changes

2021-12-09 09:43 UTC, WhiteBearSpirit approved these changes

2021-12-09 10:13 UTC, merged