HRL-1156 Добавить правило про конкатенацию строк
clearcode-tech/code-guides pull request #27
Opened 2021-10-31 16:18 UTC by ivan-anderson

2021-11-11 20:40 UTC, WhiteBearSpirit commented
На беке строки можно элегантно конкатенировать с помощью `String.join()`. Стоит потом добавить в это правило (не сейчас). На фронте, как я понимаю, так же красиво не получается, поэтому мы так не делаем?

2021-11-11 20:41 UTC, WhiteBearSpirit requested changes

2021-11-11 20:41 UTC, WhiteBearSpirit commented on commons/cr12_strings.md
> +        + " " + currentUser.getEmployeePatronymic()
Точка с запятой в конце.

2021-11-12 06:22 UTC, mpashinsky approved these changes

2021-11-26 08:05 UTC, lera12518 approved these changes

2021-11-29 04:54 UTC, WhiteBearSpirit approved these changes

2021-12-03 06:52 UTC, WhiteBearSpirit commented on commons/cr12_strings.md
> +то перенос осуществляется вместе с оператором "+". У второй строки добавляется отступ относительно первой, но у последующих
не, строка `+ "Output was: '%s'",` должна быть на шаг правее.

2021-12-03 07:08 UTC, WhiteBearSpirit commented on commons/cr12_strings.md
> +        + " " + currentUser.getEmployeeFirstName()
Насколько мне известно, нет, но пример тут именно такой, что было бы ествественно использовать `String.join(StringUtils.SPACE, ...)`.

А для плюсиков я бы взял пример чисто со строками:
```
String lyrics = "You and me fall in line \n"
    + "To be punished for unproven crimes \n"
    + "And we know that there's no one we can trust \n"
    + "Our ancient heroes, they are turning to dust";
```

2021-12-07 18:11 UTC, merged