HRL-1179 Добавить правило про try-catch
clearcode-tech/code-guides pull request #29
Opened 2021-11-10 19:56 UTC by ivan-anderson

2021-11-23 13:10 UTC, KateTarasowa commented on backend/java/jr05_try-catch.md
> +    }
Возможно стоит добавить еще пример:
 catch (InterruptedException e) {

            Thread.currentThread().interrupt();
            throw new IllegalStateException("Request to SMS sender was interrupted", e);
        }

2021-11-25 23:59 UTC, ivan-anderson commented on backend/java/jr05_try-catch.md
> +    }
могу просто заменить текущий

2021-11-26 08:03 UTC, lera12518 commented on backend/java/jr05_try-catch.md
> +
как думаешь, стоит сюда добавить правило, которое было добавлено в checkstyle -  https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/NestedTryDepthCheck.html
со стандартным значением допустимой глубины вложенности
оно выглядит очень подходящим для упоминания именно в этом разделе

2021-11-26 08:03 UTC, lera12518 commented on backend/java/jr05_try-catch.md
> +2. Каждый метод содержащий операции, которые подразумевают атомарность, должен иметь свою транзакцию.
метод, содержащий

2021-11-26 08:03 UTC, lera12518 commented on backend/java/jr05_try-catch.md
> +Даже если это приватный метод, который вызывается единожды внутри транзакции.
я бы заменила единожды на один раз, оно считается устаревшим
но можно и оставить конечно, просто непривычное

2021-11-26 10:34 UTC, KateTarasowa approved these changes

2021-11-29 06:46 UTC, mpashinsky approved these changes

2021-11-29 08:20 UTC, WhiteBearSpirit requested changes

2021-11-29 08:20 UTC, WhiteBearSpirit commented on backend/java/jr05_try-catch.md
> +2. Каждый метод содержащий операции, которые подразумевают атомарность, должен иметь свою транзакцию.
"операции, которые подразумевают атомарность" - мне кажется, не тот смысл получается. Тут важно подчеркнуть, что операции атомарные не по отдельности, а атомарно они должны все вместе выполняться.

"Каждый метод, содержащий операции, которые должны выполняться атомарно, должен иметь свою транзакцию."

2021-11-29 08:20 UTC, WhiteBearSpirit commented on backend/java/jr05_try-catch.md
> +1. Каждый метод должен обрабатывать ошибку внутри себя. Проброс ошибок `throws SomeException` в методах запрещён.
Но.. валидации... вложеннные require()...
Напиши про это исключение.

2021-12-07 18:16 UTC, ivan-anderson commented on README.md
> +- [JR05: Try-catch](backend/java/jr05_try-catch.md)
подфикшу при слитии

2021-12-07 19:13 UTC, ivan-anderson commented on backend/java/jr05_try-catch.md
> +1. Каждый метод должен обрабатывать ошибку внутри себя. Проброс ошибок `throws SomeException` в методах запрещён.
в валидации и require у нас нет throws в сигнатуре метода

2021-12-07 19:23 UTC, ivan-anderson commented on backend/java/jr05_try-catch.md
> +Даже если это приватный метод, который вызывается единожды внутри транзакции.
смысл в том, что если метод находится в сервисе и будет использоваться в различных менеджерах, то тогда понятно, что мы должны гарантировать транзакционность метода, который будет использоваться повсеместно. Но другое дело, когда ты пишешь, некий класс, и решил вынести **часть** транзакции в отдельный метод, ибо твой код стал большим, и несмотря на то, что этот маленький приватный метод будет вызван внутри транзакции, всё равно нужно обернуть его своей внутренней транзакцией.

2021-12-09 09:47 UTC, WhiteBearSpirit commented on backend/java/jr05_try-catch.md
> +1. Каждый метод должен обрабатывать ошибку внутри себя. Проброс ошибок `throws SomeException` в методах запрещён.
А, понял.

2021-12-09 11:08 UTC, WhiteBearSpirit commented on backend/java/jr05_try-catch.md
> +Даже если это приватный метод, который вызывается единожды внутри транзакции.
Понятно. Но я тут подумал, что транзакции - это вообще-то не про try-catch.
То есть надо сделать отдельное правило про транзакции, и там уж развернуться, написать и про транзакции внутри каждого метода, и проговорить про вложенные транзакции, и про особую осторожность в использовании внутри транзакций методов, которые не поддерживают транзакции (то как вызовы клиента другого сервера).

2021-12-09 11:16 UTC, WhiteBearSpirit requested changes

2021-12-09 11:16 UTC, WhiteBearSpirit commented on backend/java/jr05_try-catch.md
> +3. Максимальное количество вложенных блоков try друг в друга = 2.
В "Допустимом варианте" только один блок вложен в другой. Поэтому такая формулировка не совсем корректная. Предлгагаю оперировать термином "глубина".
А ещё обернуть try -> `try`.
```suggestion
3. Максимальная глубина вложенности блоков `try` друг в друга = 2.
```

2021-12-09 20:42 UTC, ivan-anderson commented on backend/java/jr05_try-catch.md
> +Даже если это приватный метод, который вызывается единожды внутри транзакции.
1 и 2 правило похожи по своей структуре. Думаю пока оставить так. Если кто-то займётся темой транзакций (я ближайшие 2 спринта точно не буду), то сможет перенести, а если нет, то хотя бы это будет в таком виде.

2021-12-09 20:45 UTC, ivan-anderson commented on backend/java/jr05_try-catch.md
> +3. Максимальное количество вложенных блоков try друг в друга = 2.
если уже говорим слово глубина, то это  = 1

2021-12-10 06:55 UTC, WhiteBearSpirit commented on backend/java/jr05_try-catch.md
> +Даже если это приватный метод, который вызывается единожды внутри транзакции.
Ок)

2021-12-10 06:55 UTC, WhiteBearSpirit approved these changes

2021-12-22 07:12 UTC, lera12518 approved these changes

2021-12-27 08:58 UTC, merged