HRL-1209 Добавлено описание инструмента Inspect code
clearcode-tech/code-guides pull request #30
Opened 2021-11-25 20:52 UTC by ivan-anderson

2021-11-26 07:57 UTC, lera12518 requested changes

2021-11-26 07:57 UTC, lera12518 commented on tools/tools01_inspect-code.md
> +Нам показывается окно, где можно выбрать scope поиска (его рассматривать не будем) и настройка правила.
после "и" странная формулировка. может "окно с выбором scope поиска и настройками правил"?)

2021-11-26 07:57 UTC, lera12518 commented on tools/tools01_inspect-code.md
> +После запуска мы получаем результат во вкладке Inspection Results, но просмотр через эту вкладку неудобный,
После запуска результат отображается во вкладке Inspection Results,

2021-11-26 10:32 UTC, KateTarasowa approved these changes

2021-11-29 06:44 UTC, mpashinsky commented on tools/tools01_inspect-code.md
> +Нам показывается окно, где можно выбрать scope поиска (его рассматривать не будем) и настройка правила.
Отображается окно с выбором scope поиска и настройками правил.

2021-11-29 06:45 UTC, mpashinsky approved these changes

2021-11-29 06:49 UTC, WhiteBearSpirit requested changes

2021-11-29 06:49 UTC, WhiteBearSpirit commented on tools/tools01_inspect-code.md
> +В опциях уровень инкапсуляции работает по принципу — поиск выбранного уровня и уровней вложенного в него.
В опциях уровень инкапсуляции работает по принципу: поиск по выбранному уровню и уровням, вложеным в него.

2021-11-29 06:49 UTC, WhiteBearSpirit commented on tools/tools01_inspect-code.md
> +Можно облегчить поиск выгрузив результат в XML и искать по тегу description.
Можно облегчить поиск, выгрузив результат в XML, и искать

2021-11-29 06:49 UTC, WhiteBearSpirit commented on tools/tools01_inspect-code.md
> +## Code style tools: Inspect code
Code style tools 01: Inspect code

2021-12-08 09:15 UTC, lera12518 requested changes

2021-12-08 09:15 UTC, lera12518 commented on tools/tools01_inspect-code.md
> +Inspect code это инструмент Idea с большим количеством настроек для поиска проблемных участков кода.
Inspect code - это

2021-12-08 09:15 UTC, lera12518 commented on tools/tools01_inspect-code.md
> +Хоть инструмент и можно адаптировать под различные требования проекта, но у него есть недостаток в формировании
Инструмент и можно адаптировать под различные требования проекта, но у него есть недостаток в формировании

2021-12-08 09:15 UTC, lera12518 commented on tools/tools01_inspect-code.md
> +Можно облегчить поиск, выгрузив результат в XML, и искать по тегу description.
выгрузив результат в XML - стоит написать как это сделать?

2021-12-09 09:49 UTC, WhiteBearSpirit approved these changes

2021-12-09 09:49 UTC, WhiteBearSpirit commented on tools/tools01_inspect-code.md
> +Можно облегчить поиск, выгрузив результат в XML, и искать по тегу description.
![image](https://user-images.githubusercontent.com/18743472/145373279-913ad7fa-d45e-439d-858f-c729e58b4878.png)
Export -> XML

2021-12-09 20:28 UTC, ivan-anderson commented on tools/tools01_inspect-code.md
> +Хоть инструмент и можно адаптировать под различные требования проекта, но у него есть недостаток в формировании
что-то не то написала

2021-12-22 07:12 UTC, lera12518 approved these changes

2021-12-27 13:04 UTC, merged