SR02 Insert
clearcode-tech/code-guides pull request #31
Opened 2021-12-06 10:35 UTC by WhiteBearSpirit

2021-12-07 19:54 UTC, ivan-anderson commented on backend/sql/sr02_insert.md
> +Если нет, то на новой строке пишем открывающую скобку, на следующих строках перечисляем значения,
а если без values у меня значения умещаются в одну строку, то всё равно каждое с новой строки

2021-12-07 20:06 UTC, ivan-anderson commented on backend/sql/sr02_insert.md
> +3. Если нужно задать UUID, то не используем функции для генерации (`uuid_generate_v4()` и т.п.),
лучше б сразу в правиле написать пояснение

2021-12-07 20:06 UTC, ivan-anderson approved these changes

2021-12-08 07:54 UTC, lera12518 approved these changes

2021-12-09 09:25 UTC, KateTarasowa requested changes

2021-12-09 09:25 UTC, KateTarasowa commented on backend/sql/sr02_insert.md
> +        '9a88cf55-fc92-4a59-8be9-92f0470d557e',
Мы точно так делаем?

2021-12-09 09:25 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +3. Если нужно задать UUID, то не используем функции для генерации (`uuid_generate_v4()` и т.п.),
Не понял, а сейчас оно написано не в правиле?
Но я заметил, что у меня неправильно обозначены разделы правила, пофиксил.

2021-12-09 09:26 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +2. Если вставляем несколько записей в одной инструкции, то все записи, включая первую,
Уже пофиксил)

2021-12-09 09:26 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +        '9a88cf55-fc92-4a59-8be9-92f0470d557e',
Как именно? Вставляем готовые UUID? Да, точно.

2021-12-09 12:34 UTC, KateTarasowa commented on backend/sql/sr02_insert.md
> +        '9a88cf55-fc92-4a59-8be9-92f0470d557e',
Нет, переносим строки, когда не влезает

2021-12-09 12:44 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +        '9a88cf55-fc92-4a59-8be9-92f0470d557e',
Да, это мы с Сашей обсудили. См. https://bitbucket.org/ekd-dev/ekd-monolith/pull-requests/601/hrl-1228-e-mail#comment-265441694 только у меня битбакет кривовато открывает ссылку.
Про типы документов предлагаю считать исключением, иначе там получается жёстко.

2021-12-09 20:51 UTC, ivan-anderson commented on backend/sql/sr02_insert.md
> +3. Если нужно задать UUID, то не используем функции для генерации (`uuid_generate_v4()` и т.п.),
Сейчас у тебя вообще нет пояснения почему мы делаем "согласованный" UUID, а не у каждого свой.

2021-12-13 06:29 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +3. Если нужно задать UUID, то не используем функции для генерации (`uuid_generate_v4()` и т.п.),
А я сам не знаю, зачем) Подскажите.

2021-12-13 06:41 UTC, KateTarasowa commented on backend/sql/sr02_insert.md
> +3. Если нужно задать UUID, то не используем функции для генерации (`uuid_generate_v4()` и т.п.),
Чтобы у всех тенантов были одинаковые значения

2021-12-13 06:52 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +3. Если нужно задать UUID, то не используем функции для генерации (`uuid_generate_v4()` и т.п.),
Да, но кому и что это даёт?

2021-12-13 06:53 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +3. Если нужно задать UUID, то не используем функции для генерации (`uuid_generate_v4()` и т.п.),
Чтоб поддержка могла всем тенантам что-то одинаково поправить?

2021-12-13 11:08 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +3. Если нужно задать UUID, то не используем функции для генерации (`uuid_generate_v4()` и т.п.),
Добавил пояснение.

2021-12-19 11:25 UTC, mpashinsky approved these changes

2021-12-29 13:47 UTC, WhiteBearSpirit commented on backend/sql/sr02_insert.md
> +на последней строке пишем закрывающую скобку.
Добавил

2021-12-30 07:55 UTC, KateTarasowa approved these changes

2021-12-30 07:57 UTC, merged