HRL-1285 Дополнить правило CR13
clearcode-tech/code-guides pull request #33
Opened 2021-12-12 22:57 UTC by ivan-anderson

2021-12-12 22:59 UTC, ivan-anderson commented
В задачу слит HRL-741

2021-12-13 06:43 UTC, WhiteBearSpirit commented
Если попросить Мишу заапрувить 741 и слить её в мейн, то в здесь диффе остнутся только фактичекие изменения этой ветки?

2021-12-13 06:46 UTC, WhiteBearSpirit commented on commons/cr13_call_chains.md
> +        .filter((String line) -> !line.isEmpty())
Предлагаю здесь тоже предикат использовать, как и в строке 43:
`.filter(Predicate.not(String::isEmpty))`

2021-12-13 06:49 UTC, WhiteBearSpirit approved these changes

2021-12-13 14:00 UTC, lera12518 requested changes

2021-12-13 14:00 UTC, lera12518 commented on frontend/angular/ar05_html-attributes.md
> +- Структурные директивы: `ngIf`, `ngFor`, `*ngSwitch`.
или все со *, или все без

2021-12-13 14:00 UTC, lera12518 commented on commons/cr11_naming-methods-and-variables.md
> +    Пример корректного наименования в enum:
лучше сначала корректное мне кажется

2021-12-19 08:37 UTC, mpashinsky commented on backend/java/jr03_immutable-object.md
> +2. Поля класса должны быть финализированы.
А если сам класс финализирован, нужно дополнительно финализировать поля?

2021-12-19 11:11 UTC, mpashinsky requested changes

2021-12-19 11:11 UTC, mpashinsky commented on commons/cr13_call_chains.md
> +2. Для первого многострочного выражения в цепочке вызовов, которое не уместилось в одну строку, действуют правила:
Предлагаю дополнительно помечать правила, которые IDEA может применять автоматически при форматировании кода по Ctrl+Alt+L. Например, "Автоматическое форматирование IDEA". И читающий, скопировав пример, сможет проверить, правильно ли у него настроена IDE (пока у нас нет общего файла настройки).

2021-12-21 13:36 UTC, WhiteBearSpirit commented on backend/java/jr03_immutable-object.md
> +2. Поля класса должны быть финализированы.
Определённо, нет

2021-12-27 13:55 UTC, KateTarasowa approved these changes

2021-12-29 20:46 UTC, ivan-anderson commented on commons/cr13_call_chains.md
> +2. Для первого многострочного выражения в цепочке вызовов, которое не уместилось в одну строку, действуют правила:
не понял идею. где писать пометку? а сами настройки где будут и кто их должен писать? и я не уверен, что текущее правило можно задать в IDEA (вложенный вызов должен сдвигать внешний вызов на дополнительный отступ)

2022-01-17 07:20 UTC, lera12518 approved these changes

2022-01-30 19:14 UTC, merged