HRL-1335 AR06 Сервисы и derivations
clearcode-tech/code-guides pull request #34
Opened 2021-12-28 07:44 UTC by lera12518

2021-12-28 10:06 UTC, KateTarasowa requested changes

2021-12-28 10:06 UTC, KateTarasowa commented on frontend/angular/ar06_services_and_derivations.md
> +- Методы не должны принимать в качестве параметров состояние приложения. То есть при вызове из reducer'ов необходимо передать в сервис конкретный объект состояния или их список, а также данные для об
конкретное поле состояния

2021-12-28 10:06 UTC, KateTarasowa commented on frontend/angular/ar06_services_and_derivations.md
> +- Если в рамках метода необходимо менять контекст, должен быть реализован вызов метода другого сервиса. Пример: Метод обновления сотрудника в сервисе обновляет также его каналы уведомлений. Правильны
не понятно чтот такое контекст

2021-12-28 10:11 UTC, WhiteBearSpirit requested changes

2021-12-28 10:11 UTC, WhiteBearSpirit commented on frontend/angular/ar06_services_and_derivations.md
> +## Angular Rule 6: Service и Derivations
Надо синхронизировать заголовок здесь и название в README.md. Например, здесь "Сервисы и derivations".

2021-12-28 10:11 UTC, WhiteBearSpirit commented on frontend/angular/ar06_services_and_derivations.md
> +- Методы в рамках одного сервиса должны быть объединены по семантике. Например, сервис для работы с моделью, с датами, фильтрами определенного реестра, определенным диалогом и т.д.
Переносите строки плиз, тут тоже актуален максимум в 120 символов.

2021-12-28 10:22 UTC, lera12518 commented on frontend/angular/ar06_services_and_derivations.md
> +### Service - сервис для работы с моделью или в одном контексте.
я копировала то, что мы пишем в джавадоке(сервис для работы с...).
В сервисе могут быть не только методы, но и например константы. Оставила такое описание с поправкой на формулировку " с моделью данных или связанные общим контекстом"

2021-12-28 10:25 UTC, lera12518 commented on frontend/angular/ar06_services_and_derivations.md
> +- Методы не должны принимать в качестве параметров состояние приложения. То есть при вызове из reducer'ов необходимо передать в сервис конкретный объект состояния или их список, а также данные для об
так как речь идет о reducer'ах, то передаваться будет объект состояния
а точнее, как Катя уже отметила рядом в комментарии, "конкретное поле состояния"

2021-12-28 11:30 UTC, WhiteBearSpirit commented on frontend/angular/ar06_services_and_derivations.md
> +### Service - сервис для работы с моделью или в одном контексте.
опять не так, связанные - кто?

2021-12-28 11:32 UTC, WhiteBearSpirit commented on frontend/angular/ar06_services_and_derivations.md
> +- Методы не должны принимать в качестве параметров состояние приложения. То есть при вызове из reducer'ов необходимо передать в сервис конкретный объект состояния или их список, а также данные для об
Да, так понятнее, что это конкретное поле state'а.

2021-12-28 12:56 UTC, WhiteBearSpirit commented on frontend/angular/ar06_services_and_derivations.md
> +### Service - сервис для работы с моделью данных или логикой, объединенной общим контекстом
👍

2021-12-28 13:05 UTC, WhiteBearSpirit requested changes

2021-12-28 13:05 UTC, WhiteBearSpirit commented on frontend/angular/ar06_services_and_derivations.md
> +- Расположение: _src/modules/root/services/_. Для сервисов диалогов _src/modules/root/services/dialogs_.
Двоеточие после "Для сервисов диалогов"

Либо сделать "Для сервисов диалогов" подпунктом:
- тыц.
  -  тыц.

2021-12-29 11:03 UTC, KateTarasowa approved these changes

2022-01-09 18:10 UTC, WhiteBearSpirit approved these changes

2022-01-11 07:26 UTC, KateTarasowa approved these changes

2022-02-08 14:21 UTC, ivan-anderson approved these changes

2022-02-09 07:41 UTC, merged