HRL-1374 Шаблоны для типизированного ID и интерфейса (JR10)
clearcode-tech/code-guides pull request #36
Opened 2022-01-26 10:33 UTC by lera12518

2022-01-27 13:02 UTC, WhiteBearSpirit commented
Тема, работает.

2022-01-27 13:03 UTC, WhiteBearSpirit requested changes

2022-01-27 13:03 UTC, WhiteBearSpirit commented on backend/java/jr10_typified-id.md
> +###Создание шаблонов файлов типизированных ID
После всех ### надо пробелы, иначе они не работают

2022-01-27 13:25 UTC, lera12518 commented on backend/java/jr10_typified-id.md
> +###Создание шаблонов файлов типизированных ID
а я как раз пыталась понять, почему не работает... в идее в превью показывает правильно без пробела

2022-01-27 13:48 UTC, WhiteBearSpirit approved these changes

2022-01-28 07:08 UTC, KateTarasowa approved these changes

2022-02-09 07:36 UTC, merged