HRL-1404 Добавлено правило наименование ID переменных JR14
clearcode-tech/code-guides pull request #37
Opened 2022-01-28 22:17 UTC by ivan-anderson

2022-02-09 07:35 UTC, lera12518 approved these changes

2022-02-09 07:35 UTC, lera12518 commented on backend/java/jr14_naming_id_variables.md
> +то следует придерживаться правила наименования:
правилу

2022-02-09 14:52 UTC, WhiteBearSpirit requested changes

2022-02-09 14:52 UTC, WhiteBearSpirit commented on README.md
> +- [JR14: Наименование ID переменных](backend/java/jr14_naming_id_variables.md)
"Именование" мне кажется точнее

2022-02-09 14:52 UTC, WhiteBearSpirit commented on README.md
> +- [JR14: Наименование ID переменных](backend/java/jr14_naming_id_variables.md)
И далее в самом правиле

2022-02-09 14:52 UTC, WhiteBearSpirit commented on backend/java/jr14_naming_id_variables.md
> +Если в рамках одного метода потребуется ввести 2 или 3 ID переменные одной и той же модели, но разных типов данных,
Я б чутка переформулировал:
```suggestion
Если в рамках одного метода требуется ввести несколько переменных с ID одной и той же модели, но с разными типами данных,
```

2022-02-09 14:52 UTC, WhiteBearSpirit commented on backend/java/jr14_naming_id_variables.md
> +
Пример:

2022-02-09 14:52 UTC, WhiteBearSpirit commented on backend/java/jr14_naming_id_variables.md
> + - `String` -> someId+AsString
Я думаю, надо добавить пояснений, who is who:

>  - `String` (ID в виде строки) -> someId+AsString
>  - `UUID` (ID в виде UUID) -> someId+Value
>  - `SomeId` (Типизированный ID) -> someId

2022-02-17 12:06 UTC, KateTarasowa approved these changes

2022-03-17 08:27 UTC, WhiteBearSpirit approved these changes

2022-03-17 09:20 UTC, merged