HRL-1405 Добавлено правило о мапперах  JR15
clearcode-tech/code-guides pull request #38
Opened 2022-01-28 23:29 UTC by ivan-anderson

2022-01-31 14:29 UTC, lera12518 requested changes

2022-01-31 14:29 UTC, lera12518 commented on backend/java/jr15_mappers.md
> +`Маппер для преобразования {@link DocumentSentToSigningResult} в {@link SentToSigningDocumentDTO}`.
вроде Никита сказал на обсуждении, что маппер - не подходящее слово и нужно "Сервис для предбразования"

2022-01-31 14:29 UTC, lera12518 commented on backend/java/jr15_mappers.md
> +Мапперы помогают убрать из менеджеров код не имеющий отношение к бизнес-логике, но в сервисах допускается построение
код, не имеющий отношение

2022-02-01 08:37 UTC, lera12518 requested changes

2022-02-01 08:37 UTC, lera12518 commented on backend/java/jr15_mappers.md
> +
не хватает упоминания, что необходимо забиндить реализацию маппера для соответствующего сервера (в данный момент есть EkdMapperModule)

2022-02-01 08:40 UTC, lera12518 commented on backend/java/jr15_mappers.md
> +
UPD обсудили с Сашей, что можно инжектить поля в виде 
`private final CreateUnconfirmedUserDTOMapper createUnconfirmedUserDataMapper;`
а не 
`private final Mapper<List<DocumentSentToSigningResult>, List<SentToSigningDocumentDTO>> mapper;`

2022-02-01 08:40 UTC, lera12518 commented on backend/java/jr15_mappers.md
> +
тогда биндинг не нужен

2022-02-09 07:34 UTC, lera12518 approved these changes

2022-02-09 15:14 UTC, WhiteBearSpirit requested changes

2022-02-09 15:14 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers.md
> +2. Наименование реализации производить по правилу:
"Именование"?

2022-02-09 15:14 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers.md
> +- для DTO, Data, Details -> название класса - суффикс (DTO, Data, Details) + Mapper
" - суффикс" не очень читается как "минус суффикс". Я б предложил 
> {название класса без суффикса} + Mapper

2022-02-09 15:14 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers.md
> +- для DTO, Data, Details -> название класса - суффикс (DTO, Data, Details) + Mapper
Data мы, кажется, не используем

2022-02-09 15:14 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers.md
> +3. Реализации размещать в директории .../business_logic/services/mappers.
может, "в пакетах"?

2022-02-09 15:14 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers.md
> +моделей перед отправкой их в БД - в сервисах можно обойтись без маппера.
Лексический повтор, лучше
```suggestion
моделей перед отправкой их в БД - там можно обойтись без маппера.
```

2022-02-11 12:06 UTC, ivan-anderson commented on backend/java/jr15_mappers.md
> + - для моделей -> название класса + Mapper
для мапперов, где результатом является модель

2022-02-11 12:07 UTC, ivan-anderson commented on backend/java/jr15_mappers.md
> +- для DTO, Data, Details -> название класса - суффикс (DTO, Data, Details) + Mapper
для мапперов, где результатом являются DTO, Data, Details

2022-02-17 07:35 UTC, lera12518 commented on backend/java/jr15_mappers.md
> +- для DTO, Data, Details -> название класса - суффикс (DTO, Data, Details) + Mapper
используем же

2022-02-17 07:37 UTC, lera12518 commented on backend/java/jr15_mappers.md
> +Mapper<SomeEntity, SomeDTO> или Mapper2<SomeEntity, AnotherEntity, SomeDTO>.
я уже делаю по итогам ревью в коммонсе TenantMaper5 на основании Mapper5, который тоже создам. то есть максимум 5, но с учетом тенанта видимо

2022-02-17 07:38 UTC, lera12518 commented on backend/java/jr15_mappers.md
> +- для DTO, Data, Details -> название класса - суффикс (DTO, Data, Details) + Mapper
а зачем делить "- для моделей" и для "- для DTO, Data, Details", если логика одна и та же? имя класса + Mapper? или лучше подробнее так оставить?

2022-02-17 12:37 UTC, KateTarasowa requested changes

2022-02-17 12:37 UTC, KateTarasowa commented on backend/java/jr15_mappers.md
> +1. Код построения DTO и моделей (builder()...build()) должен располагаться внутри реализации интерфейса
не очень понятно, что значит построения, не все же построения должны быть в мепперах, может лучге писать: Код преобразование DTO или моделей в другую DTO или модель. Или что-то подобное

2022-02-22 11:39 UTC, WhiteBearSpirit requested changes

2022-02-22 11:39 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers.md
> + - для моделей -> название класса + Mapper
```suggestion
 - Для мапперов, где результатом является модель: название модели + Mapper
```

2022-02-22 11:39 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers.md
> +- для DTO, Data, Details -> название класса - суффикс (DTO, Data, Details) + Mapper
И с большой буквы плз.

2022-03-10 10:27 UTC, ivan-anderson commented on backend/java/jr15_mappers.md
> +
добавить пояснение, когда прибегаем к Mapper вместо статик фабрик:
Из слака 

> DTO сама может и должна быть ответствена за хитрости и сложности её формирования. Допустим у тебя есть DTO_1 и из неё ты хочешь сформировать DTO_2, то mapper делать необходимо только если необходимо обращаться к каким-то сервисам, либо DTO_2 в commons, а DTO_1 нет (т.е. нет возможности внести логику mapping'а внутрь DTO_2).

2022-03-30 06:07 UTC, KateTarasowa requested changes

2022-03-30 06:07 UTC, KateTarasowa commented on backend/java/jr15_mappers_and_static_factory.md
> +создание сущностей перед отправкой их в БД - там можно обойтись без маппера и фабрики.
уже не допускается создание сущностей в сервисе, там теперь надо выносить. Может убрать упоминание о серсисах?

2022-03-30 06:07 UTC, KateTarasowa commented on backend/java/jr15_mappers_and_static_factory.md
> +3. Именование реализации производить по правилу: название класса результата преобразования + Mapper
а если есть 2 мапера и они преобразуют в одну можель?

2022-03-30 06:07 UTC, KateTarasowa commented on backend/java/jr15_mappers_and_static_factory.md
> +`Сервис для преобразования {@link DocumentSentToSigningResult} в {@link SentToSigningDocumentDTO}`.
Может как отобразить тот факт, что, если один из параметров из которого идет преобразование это String, то надо писать словами, что он значить, а не ссылатся на String

2022-03-30 07:27 UTC, WhiteBearSpirit requested changes

2022-03-30 07:27 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers_and_static_factory.md
> +1. Код для создания экземпляра должен находится в статической фабрике данного класса. Исключением являются сущности
"должен" - звучит как преувеличение, есть другие варианты, те же мапперы, или по-старинке билдером, или может даже конструктором.

2022-03-30 07:27 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers_and_static_factory.md
> +(@Entity).
А почему для Entity нельзя?

2022-03-30 07:27 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers_and_static_factory.md
> +`Сервис для преобразования {@link DocumentSentToSigningResult} в {@link SentToSigningDocumentDTO}`.
А также, что можно, но не строго обязательно, все элементы преобразования писать словами, а не link.

2022-03-30 07:27 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers_and_static_factory.md
> +3. Именование реализации производить по правилу: название класса результата преобразования + Mapper
Я бы предложил {{SourceClass}}To{{DestinationClass}}Mapper.
Если исходных классов несколько, то, возможно, стоит выделить основной и его написать в {{SourceClass}}.

2022-03-30 07:32 UTC, WhiteBearSpirit commented on backend/java/jr15_mappers_and_static_factory.md
> +
Хочется какого-то вступления. Например:
Для создания экземпляров моделей и объектов для передачи данных нужно использовать статические фабрики и мапперы.

2022-06-16 14:33 UTC, ivan-anderson commented on README.md
> +- [JR15: Мапперы](backend/java/jr15_mappers.md)
не уверен, что прочитав "Мапперы" потребуются пояснения. а за "сервисы для преобразования данных" глаз не цепляется. @lera12518 @KateTarasowa что думаете?

2022-07-04 19:22 UTC, WhiteBearSpirit approved these changes

2022-08-01 06:35 UTC, KateTarasowa requested changes

2022-08-01 06:35 UTC, KateTarasowa commented on backend/java/jr15_mappers.md
> +Мапперы создаются в отдельном классе реализуя интерфейсы Mapper, Mapper2, Mapper3, Mapper4 и Mapper5.
еще есть TenantMapper5

2022-08-01 06:35 UTC, KateTarasowa commented on README.md
> +- [JR15: Мапперы](backend/java/jr15_mappers.md)
Согласна с Ваней

2022-08-18 23:08 UTC, merged