HRL-1439 AR04 Обновить настройки и описание Stylelint
clearcode-tech/code-guides pull request #40
Opened 2022-02-08 12:44 UTC by WhiteBearSpirit

2022-02-08 15:14 UTC, ivan-anderson commented on frontend/angular/ar04_css-properties-order.md
> +     `<project>/stylelint.config.js`
нет такой настройки и Run for files на старой версии IDEA =\

2022-02-09 14:30 UTC, WhiteBearSpirit commented on frontend/angular/ar04_css-properties-order.md
> +     `<project>/stylelint.config.js`
Добавил пояснение, чтобы люди не пугались. Если настройки нет - то и фиг с ней. Но вообще, с шансами у человека, который будет заново ставить линтеры - будет и Идея свежая.

2022-02-17 12:04 UTC, KateTarasowa requested changes

2022-02-17 12:04 UTC, KateTarasowa commented on frontend/angular/ar04_css-properties-order.md
> +4. Создать файл конфигурации `stylelint.config.js`. Для генерации файла можно воспользоваться пакетом
Он же уже создан в проекте.

2022-02-17 12:11 UTC, lera12518 commented on frontend/angular/ar04_css-properties-order.md
> +4. Создать файл конфигурации `stylelint.config.js`. Для генерации файла можно воспользоваться пакетом
тоже хотела спросить
но там нет ""customSyntax": "postcss-less", " в проекте кстати

2022-02-25 09:04 UTC, WhiteBearSpirit commented on frontend/angular/ar04_css-properties-order.md
> +4. Создать файл конфигурации `stylelint.config.js`. Для генерации файла можно воспользоваться пакетом
@KateTarasowa Это ж раздел "Установка Stylelint в UI-проект". Его изначально нет в проекте.

2022-02-25 09:05 UTC, WhiteBearSpirit commented on frontend/angular/ar04_css-properties-order.md
> +4. Создать файл конфигурации `stylelint.config.js`. Для генерации файла можно воспользоваться пакетом
@lera12518 Для этого у этой же задачи есть пуллреквест в битбакете, добавляющий `"customSyntax": "postcss-less",`
https://bitbucket.org/ekd-dev/%7Bcab0cbec-0d9d-4e1b-ba1c-c4fa3fea7eff%7D/pull-requests/345

2022-02-25 10:11 UTC, KateTarasowa approved these changes

2022-02-25 10:11 UTC, lera12518 approved these changes

2022-03-14 03:41 UTC, ivan-anderson approved these changes

2022-03-17 10:02 UTC, merged