HRL-1444 Добавлено правило наименования DTO и валидаторов JR16
clearcode-tech/code-guides pull request #41
Opened 2022-02-08 21:34 UTC by ivan-anderson

2022-02-09 07:32 UTC, lera12518 approved these changes

2022-02-09 07:32 UTC, lera12518 commented on backend/java/jr16_naming_dto_and_validators.md
> +1. При наименовании DTO следует придерживаться правила:
правилу

2022-02-09 14:24 UTC, WhiteBearSpirit requested changes

2022-02-09 14:24 UTC, WhiteBearSpirit commented on README.md
> +- [JR16: Наименование DTO и валидаторов](backend/java/jr16_naming_dto_and_validators.md)
В аналогичных местах было "Именование", и мне оно больше нравится, т.к. указывает на процесс создания имени, давай тут тоже?

2022-02-09 14:24 UTC, WhiteBearSpirit commented on README.md
> +- [JR16: Наименование DTO и валидаторов](backend/java/jr16_naming_dto_and_validators.md)
Плюс правил становится много, уже сложновато находить нужные. Было бы классно обсудить, по какому принципу их стоит разбивать. Например, мне было бы удобно в одном правиле прочитать всё про DTO, в другом - всё про валидаторы и т.д. Но это так, мысли на будущее.

2022-02-09 14:24 UTC, WhiteBearSpirit commented on backend/java/jr16_naming_dto_and_validators.md
> +## Java Rule 16: Наименование DTO и валидаторов
"Именование", или есть особые причины для "наименования"?

2022-02-09 14:24 UTC, WhiteBearSpirit commented on backend/java/jr16_naming_dto_and_validators.md
> +## Java Rule 16: Наименование DTO и валидаторов
И далее по тексту - тоже.

2022-02-17 11:57 UTC, KateTarasowa requested changes

2022-02-17 11:57 UTC, KateTarasowa commented on backend/java/jr16_naming_dto_and_validators.md
> +совершается операция + DTO. Пример: `CreateUnconfirmedUserDTO`.
может лучше прилагательн**ые**?
И что в таком случае: Базовые данные сертификата человека? Должно быть PersonCertificateBaseDTO или BasePersonCertificateDTO?

2022-03-14 03:01 UTC, ivan-anderson commented on backend/java/jr16_naming_dto_and_validators.md
> +совершается операция + DTO. Пример: `CreateUnconfirmedUserDTO`.
Думается что правильный порядок PersonCertificateBaseDTO

2022-03-14 11:34 UTC, KateTarasowa approved these changes

2022-03-17 09:19 UTC, WhiteBearSpirit approved these changes

2022-03-17 09:22 UTC, merged