HRL-1460 NGRX01 State
clearcode-tech/code-guides pull request #43
Opened 2022-03-11 12:00 UTC by lera12518

2022-03-14 03:37 UTC, ivan-anderson commented on frontend/ngrx/ngrx01-state.md
> +- State должен быть логически правильным. Не стоит перегружать state различными данными, для каждых данных лучше создать
без примера этот пункт непонятный

2022-03-15 13:53 UTC, lera12518 commented on frontend/ngrx/ngrx01-state.md
> +- State должен быть логически правильным. Не стоит перегружать state различными данными, для каждых данных лучше создать
добавила пример. если есть ещё идеи примеров - жду предложений:) 
ps если появятся еще примеры, наверн будет достойно отдельного пункта

2022-03-30 06:18 UTC, KateTarasowa requested changes

2022-03-30 06:18 UTC, KateTarasowa commented on frontend/ngrx/ngrx01-state.md
> +- для данных, связанных с состоянием - undefined
что значит: для данных, связанных с состоянием ?

2022-03-30 06:18 UTC, KateTarasowa commented on frontend/ngrx/ngrx01-state.md
> +- Уникальные для диалоговых окон: _opened_ (открыт ли диалог), _pending_ (действие, для которого предназначен диалог,
может лучше написать: Находится ли в процессе выполнения действие, для которого предназначен диалог

2022-04-04 10:25 UTC, lera12518 commented on frontend/ngrx/ngrx01-state.md
> +- для данных, связанных с состоянием - undefined
поправила формулировку

2022-04-04 10:32 UTC, KateTarasowa approved these changes

2022-04-04 13:20 UTC, WhiteBearSpirit requested changes

2022-04-04 13:20 UTC, WhiteBearSpirit commented on frontend/ngrx/ngrx01-state.md
> +перегружен. Нужно создать отдельное состояние для фильтров реестра. В состояние
В состояние чего?

2022-04-04 13:20 UTC, WhiteBearSpirit commented on frontend/ngrx/ngrx01-state.md
> +- Уникальные для диалоговых окон: _opened_ (открыт ли диалог), _pending_ (Находится ли в процессе выполнения действие,
Тут прям просится выделение `code`.
```suggestion
- Уникальные для диалоговых окон: `opened` (открыт ли диалог), `pending` (Находится ли в процессе выполнения действие, 
```

2022-04-04 13:20 UTC, WhiteBearSpirit commented on frontend/ngrx/ngrx01-state.md
> +меняет входящие данные, он передает событие изменения входящих данных в умный компонент, тот диспатчит событие
Может диспатчит -> бросает?

2022-04-04 13:20 UTC, WhiteBearSpirit commented on frontend/ngrx/ngrx01-state.md
> +- State обычно не хранит флаг loaded, он определяется в селекторе на основании наличия данных в состоянии.
> `loaded`

2022-04-04 13:20 UTC, WhiteBearSpirit commented on frontend/ngrx/ngrx01-state.md
> +NgRx Store (хранилище) хранит в себе глобальное состояние Angular приложения в виде одного большого объекта.
Мне кажется классным выделять **Store** и **State** жирным. Не знаю, насколько это соответствует твоему эстетическому чувству, может, не жирным, а чем-то другим.

2022-04-04 13:20 UTC, WhiteBearSpirit commented on frontend/ngrx/ngrx01-state.md
> +- для boolean полей - false;
```suggestion
- Для `boolean` полей - `false`.
```
и так далее.

2022-04-07 11:51 UTC, lera12518 commented on frontend/ngrx/ngrx01-state.md
> +перегружен. Нужно создать отдельное состояние для фильтров реестра. В состояние
ничего:)

2022-04-07 11:51 UTC, lera12518 commented on frontend/ngrx/ngrx01-state.md
> +меняет входящие данные, он передает событие изменения входящих данных в умный компонент, тот диспатчит событие
согласна

2022-04-07 11:54 UTC, lera12518 commented on frontend/ngrx/ngrx01-state.md
> +NgRx Store (хранилище) хранит в себе глобальное состояние Angular приложения в виде одного большого объекта.
ну я выделила, но может переборщила

2022-04-07 11:56 UTC, lera12518 commented on frontend/ngrx/ngrx01-state.md
> +- для boolean полей - false;
это неполноценные предложения, мне в данном случае такой список больше нравится. но в кавчки обернула

2022-04-07 13:33 UTC, WhiteBearSpirit commented on frontend/ngrx/ngrx01-state.md
> +- для `boolean` полей - `false`;
с точкой с запятой надо что-то делать, почему она только тут?

2022-05-16 07:52 UTC, lera12518 commented on frontend/ngrx/ngrx01-state.md
> +- State обычно не хранит флаг loaded, он определяется в селекторе на основании наличия данных в состоянии.
`boolean`

2022-05-16 07:52 UTC, lera12518 commented on frontend/ngrx/ngrx01-state.md
> +- для `boolean` полей - `false`;
поставила везде

2022-05-26 07:24 UTC, ivan-anderson approved these changes

2022-05-26 08:55 UTC, merged