HRL-1569 SR03 Именование внешних ключей
clearcode-tech/code-guides pull request #44
Opened 2022-03-16 06:25 UTC by lera12518

2022-03-30 06:18 UTC, KateTarasowa requested changes

2022-03-31 09:42 UTC, WhiteBearSpirit requested changes

2022-03-31 09:42 UTC, WhiteBearSpirit commented on backend/sql/sr03_fk-naming.md
> +**Сокращение производится по первым буквам составляющих слов имени, в том числе для поля с именем _id_(сокращается до i)**
А почему именно это предложение выделено жирным? На заголовок не тянет)

2022-03-31 09:42 UTC, WhiteBearSpirit commented on backend/sql/sr03_fk-naming.md
> +**Сокращение производится по первым буквам составляющих слов имени, в том числе для поля с именем _id_(сокращается до i)**
Надо бы пробел после `_id_`

2022-03-31 09:42 UTC, WhiteBearSpirit commented on backend/sql/sr03_fk-naming.md
> +Пример создания внешнего ключа для столбца _some_column_name_ таблицы _some_table_name_ на столбец another_column_name
_another_column_name_ курсивом

2022-03-31 09:42 UTC, WhiteBearSpirit commented on backend/sql/sr03_fk-naming.md
> +таблицы another_table_name:
_another_table_name_ курсивом

2022-03-31 09:42 UTC, WhiteBearSpirit commented on backend/sql/sr03_fk-naming.md
> +Внешний ключ (FK) именуется на основании четырех имен: зависимой таблицы, столбца, зависимого от другой таблицы,
Как билдить имя - расписано далее. А для читаемости этого перечисления я предлагаю использовать список:

> ... на основании четырех имен:
> 1. Зависимой таблицы.
> 2. Столбца, зависимого от другой таблицы.
> 3. Главной таблицы.
> 4. Столбца главной таблицы, на который ссылается внешний ключ.

+ обратите внимание на замену "указывает" -> "ссылается"

2022-04-04 13:23 UTC, WhiteBearSpirit commented on backend/sql/sr03_fk-naming.md
> +**Сокращение производится по первым буквам составляющих слов имени, в том числе для поля с именем _id_(сокращается до i)**
А чего ты резолвишь коммент, ничего не меняя и не отвечая?

2022-04-04 13:27 UTC, WhiteBearSpirit commented on backend/sql/sr03_fk-naming.md
> +- Длина имени для FK ограничено 63 символами (с учетом начала имени `fk_`, 60 символов) на имена столбцов и полей.
Ну теперь тут дефис надо:

> с учетом начала имени `fk_` - 60 символов

2022-04-04 13:28 UTC, WhiteBearSpirit approved these changes

2022-04-04 13:29 UTC, WhiteBearSpirit commented on backend/sql/sr03_fk-naming.md
> +- Длина имени для FK ограничено 63 символами (с учетом начала имени `fk_`, 60 символов) на имена столбцов и полей.
ограничен**а** 63 символами

2022-04-07 11:49 UTC, lera12518 commented on backend/sql/sr03_fk-naming.md
> +- Длина имени для FK ограничено 63 символами (с учетом начала имени `fk_`, 60 символов) на имена столбцов и полей.
тире)

2022-05-23 06:50 UTC, KateTarasowa approved these changes

2022-05-26 07:27 UTC, ivan-anderson approved these changes

2022-05-26 08:53 UTC, merged