HRL-1463 JR17 Mетоды формирования моделей
clearcode-tech/code-guides pull request #45
Opened 2022-04-05 09:23 UTC by KateTarasowa

2022-04-07 12:22 UTC, lera12518 requested changes

2022-04-07 12:22 UTC, lera12518 commented on backend/java/jr17_methods_to_builder_models.md
> +   Исключение - когда внутри одного класса в рамках многих разных методов формируется последовательно объект.
в слаке писали https://hr-linkdevteam.slack.com/archives/C02NJ8PJY76/p1649328853445639
эту логику тоже стоит внести в статью

2022-04-07 12:22 UTC, lera12518 commented on backend/java/jr17_methods_to_builder_models.md
> +2. Правила наименования
стоит учесть то, что обсудили и переформулировать
про то, что названия должны быть бизнесовые, если им можно дать логичное бизнесовое имя (как с buildNewSentToSigningDraft)
про create видимо отдельно надо дописать, что это static factory, называть можно бизнесово или build/of

2022-04-07 12:22 UTC, lera12518 commented on backend/java/jr17_methods_to_builder_models.md
> +  Имена методов необходимо выбирать так, чтобы при усложнении логики метода не было необходимости менять наименование
не очень понимаю, что значит `не было необходимости менять наименование`
наименование -> название/имя
можнео добавить пример или переформулировать

2022-04-07 12:22 UTC, lera12518 commented on backend/java/jr17_methods_to_builder_models.md
> +            .id(null)
какой-то странный пример с null'ами, может заменить на не нулы? особенно .id(null)

2022-04-29 07:39 UTC, KateTarasowa commented on backend/java/jr17_methods_to_builder_models.md
> +            .id(null)
так это реальный пример из кода

2022-05-16 07:50 UTC, lera12518 approved these changes

2022-06-16 09:01 UTC, ivan-anderson commented on backend/java/jr17_methods_to_builder_models.md
> +1. В сервисах моделей при создании и обновлении использование `.builder()` и `.toBuilder()` должно быть вынесено в модель, на котором вызывается `.builder()` и`.toBuilder()`.
вроде можно удалить `, на котором вызывается `.builder()` и`.toBuilder()`` не потеряв смысл

2022-06-16 09:06 UTC, ivan-anderson commented on backend/java/jr17_methods_to_builder_models.md
> +2. Правила наименования.
видел варианты, которых тут нет. можно либо убрать этот пункт, либо пояснить, что это не строгое правило

2022-06-16 09:10 UTC, ivan-anderson commented on backend/java/jr17_methods_to_builder_models.md
> +Если метод предполагает создание новой модели, то он должен находиться в static factories и называться build/of.
примеров с фабриками build не нашёл. точно нужно указывать такой вариант?

2022-06-20 12:34 UTC, WhiteBearSpirit commented on backend/java/jr17_methods_to_builder_models.md
> +1. В сервисах моделей при создании и обновлении использование `.builder()` и `.toBuilder()` должно быть вынесено в модель, на котором вызывается `.builder()` и`.toBuilder()`.
Какая-то рекурсивная по смыслу фраза. + опечатка: модель, на которо**й**

2022-08-01 06:42 UTC, KateTarasowa commented on backend/java/jr17_methods_to_builder_models.md
> +Если метод предполагает создание новой модели, то он должен находиться в static factories и называться build/of.
Мы говорили, что так можно, просто пока никто не стал использовать build. Но так как мы обсуждали что так можно, то я оставлю.

2022-08-03 07:53 UTC, WhiteBearSpirit requested changes

2022-08-03 07:53 UTC, WhiteBearSpirit commented on backend/java/jr17_methods_to_builder_models.md
> +1. В сервисах моделей при создании и обновлении использование `.builder()` и `.toBuilder()` должно быть вынесено в модель, на котором вызывается `.builder()` и`.toBuilder()`.
Опечатку поправили, но по смыслу фраза осталась странная.
Предлагаю:

> Создание и обновление модели должно производиться методами самой модели. Стандартным способом является использование `.builder()` и `.toBuilder()`.

2022-08-18 23:14 UTC, ivan-anderson approved these changes

2022-10-21 10:33 UTC, KateTarasowa commented on backend/java/jr17_methods_to_builder_models.md
> +1. В сервисах моделей при создании и обновлении использование `.builder()` и `.toBuilder()` должно быть вынесено в модель, на котором вызывается `.builder()` и`.toBuilder()`.
+

2022-10-21 10:45 UTC, WhiteBearSpirit approved these changes

2022-10-21 11:10 UTC, merged