HRL-1810 JR18 Daemons и transitions
clearcode-tech/code-guides pull request #47
Opened 2022-06-15 14:11 UTC by ivan-anderson

2022-06-16 08:49 UTC, WhiteBearSpirit requested changes

2022-06-16 08:49 UTC, WhiteBearSpirit commented on backend/java/jr18_daemons_and_transitions.md
> +####1. Состояния задачи
Видимо, без пробела после # не рендерится заголовок.

2022-06-16 08:49 UTC, WhiteBearSpirit commented on backend/java/jr18_daemons_and_transitions.md
> +Состояния задачи, по которым перемещается state machine, создаём с помощью enum. Не путать с Type и Status энумами.
Яб сказал "Не путать с перечислениями Type и Status"

2022-06-16 08:49 UTC, WhiteBearSpirit commented on backend/java/jr18_daemons_and_transitions.md
> +Перечислять состояния следует придерживаясь порядка перехода задачи по ним — от начального до конечного.
Кажется, надо зпт после "следует"

2022-06-16 08:49 UTC, WhiteBearSpirit commented on backend/java/jr18_daemons_and_transitions.md
> +     * <p>Запрос завершился неуспешно.</p>
Ещё можно обсудить, как лучше писать: неуспешно или неудачно?

2022-06-16 08:49 UTC, WhiteBearSpirit commented on backend/java/jr18_daemons_and_transitions.md
> +## Java Rule 18: Daemons и Transitions
Я думаю, что основной предмет обсуждения - это состояния задач, так что стоит назвать правило `Task states`.
и в README.md

2022-06-16 10:34 UTC, ivan-anderson commented on backend/java/jr18_daemons_and_transitions.md
> +## Java Rule 18: Daemons и Transitions
нюансов в демонах и транзишенах достаточно, почему бы не агрегировать их в одном месте? а статусы пока будут первый пунктом

2022-06-16 10:41 UTC, ivan-anderson commented on backend/java/jr18_daemons_and_transitions.md
> +     * <p>Запрос завершился неуспешно.</p>
эт копипаста с проекта. не уверен, что и на такое нужно вводить жесткое правило, хотя мне больше нра "неудачно"

2022-06-16 11:25 UTC, WhiteBearSpirit approved these changes

2022-07-22 11:36 UTC, lera12518 approved these changes

2022-07-22 11:36 UTC, lera12518 commented on backend/java/jr18_daemons_and_transitions.md
> +## Java Rule 18: Daemons и Transitions
я согласна с @ivan-anderson 
делать отдельные статьи на каждую инфу по демонам звучит излишне

2022-07-22 11:36 UTC, lera12518 commented on backend/java/jr18_daemons_and_transitions.md
> +     * <p>Запрос завершился неуспешно.</p>
а мне больше нрав неуспешно, потому что на SUCCEEDED написано успешно
если говорить сравнивая с удачно/неудачно, то кажется, что "удача" меньше всего влияет на то, попала ли в это состояние задача)
но в целом я тоже за то, чтобы не вводить жесткое правило)

2022-08-01 06:37 UTC, KateTarasowa approved these changes

2022-08-03 07:32 UTC, WhiteBearSpirit approved these changes

2022-08-18 22:56 UTC, merged