GR-03 Разрешение конфликтов при релизе
clearcode-tech/code-guides pull request #7
Opened 2021-05-12 20:48 UTC by yunikita

2021-05-12 20:55 UTC, yunikita commented on git/gr03_resolving-release-conflicts.md
> +
Эти пустые строки оставляет по умолчанию Typora. Кроме того она оставляет дополнительную пустую строку между элементами списка, которые я удалил. Т.к. Typora довольно удобная, и github не отображает эти пустые строки, то думаю можно такие вещи не чистить каждый раз?

2021-05-13 07:48 UTC, bovin-a commented on git/gr03_resolving-release-conflicts.md
> +
Согласен, думаю нет смысла вычищать.

2021-05-13 07:57 UTC, bovin-a requested changes

2021-05-13 07:57 UTC, bovin-a commented on git/gr03_resolving-release-conflicts.md
> +1. Переключиться в своём локальном git-репозитории проекта на релизную ветку задачи (имя ветки можно найти в pull request'е ветки сливаемой в релизную ветку задачи, или можно уточнить у коллег)
Во всех предложениях, которые не заканчиваются двоеточием, чтобы показать какую-то команду, нужно поставить точки.

2021-05-13 07:57 UTC, bovin-a commented on git/gr03_resolving-release-conflicts.md
> +1. Переключиться в своём локальном git-репозитории проекта на релизную ветку задачи (имя ветки можно найти в pull request'е ветки сливаемой в релизную ветку задачи, или можно уточнить у коллег)
Запятая перед `или можно уточнить` не нужна, т.к. через ИЛИ и это не разные предложения, а одно из двух частей.

2021-05-13 07:57 UTC, bovin-a commented on git/gr03_resolving-release-conflicts.md
> +9. Проверить в UI pull request'а (в bitbucket'е или github'е), что ветка была успешно слита
По красоте добавить скриншот из битбакета, где видно бейдж `Merged`.

2021-05-13 07:57 UTC, bovin-a commented on git/gr03_resolving-release-conflicts.md
> +   если предыдущая команда показала, что что-то не добавлено в будущий коммит слития, то добавить все изменения можно следующей командой:
Мне кажется, что если слово `если` написать с большой буквы, то будет красивее смотреться.

2021-05-14 05:18 UTC, bovin-a approved these changes
Огонь, всё круто.

2021-05-14 05:18 UTC, merged